# Generated by Django 3.2.4 on 2023-05-25 11:12

from django.db import migrations, models
import test_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20230525_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=test_app.models.recipe_image_file_path),
        ),
    ]
